
Imports System
Module Program
    Sub Main(args As String())
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.WriteLine("WHEN THE IMPOSTER IS SUS")
        Console.Read()
    End Sub
End Module
